name: "Deno"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"

    steps:
      - id: "checkout"
        name: "Checkout code"
        uses: actions/checkout@v4

      - id: "setup"
        name: "Setup Deno"
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - id: "test"
        name: "Run tests"
        run: deno test -A

  lint:
    name: "lint"
    runs-on: "ubuntu-latest"

    steps:
      - id: "checkout"
        name: "Checkout code"
        uses: actions/checkout@v4

      - id: "setup"
        name: "Setup Deno"
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - id: "check_fmt"
        name: "Verify formatting"
        run: deno fmt --check

      - id: "lint"
        name: "Run linter"
        run: deno lint
